### ISSUE TITLE
Une minute par API (en plus des startups)

### ISSUE THREAD

**Issue by maukoquiroga** [betagouv/standup#17]
Filtrant les API qui sont faites par la DINSIC

**Comment by gregoirenovel** [comment]
Rappel : cette proposition a été faite pour permettre à OpenFisca (qui n'est plus présenté comme une Startup d'État sur beta.gouv.fr) d'apparaitre au standup hebdomadaire.

Limitations si on se base sur https://api.gouv.fr/apis :
- deux API ([API Prélèvements sociaux](https://api.gouv.fr/api/api-prelevements-sociaux.html) et [Médicapi](https://api.gouv.fr/api/medicapi.html)) sont faites par la DINSIC mais n'ont jamais été évoquée au standup
- plusieurs API d'AGV sont également présentes en tant que Startups d'État sur BGV (API Géo, API Entreprise, API Particulier, Le.Taxi, API Drones, BAN), et seraient donc traitées 2 fois si on se base sur 2 sources (AGV filtrée et BGV). À noter sur ce sujet que @MattiSG [n'est pas à l'aise avec le fait que API Entreprise et API Géo soient référencées sur BGV](https://github.com/sgmap/beta.gouv.fr/pull/763#issuecomment-313720123) et qu'il faut donc probablement creuser un peu le sujet

**Comment by Morendil** [comment]
La stratégie "fake it until you make it" évoquée lors du séminaire: au lieu de se brancher sur une API dynamique, réaliser à la main le JSON souhaité du standup, et s'assurer qu'il convient à tous les participants; ensuite seulement, chercher à encoder les règles qui génèreraient ce JSON à partir des API d'exposition des catalogues de produits.

**Comment by gregoirenovel** [comment]
Le problème initial ("permettre à OpenFisca d'apparaitre au standup hebdomadaire") a été reglé par #24 et #29, je ferme.

Subsiste le problème côté BGV de la représentation d'OpenFisca (et par extension, d'Alpha).
