### ISSUE TITLE
Go back and forth

### ISSUE THREAD

**Issue by nbrohee** [betagouv/standup#19]
L'outil permet uniquement de passer à la start-up suivante:
- A échéance du temps imparti
- Suite à clique n'importe où sur la page.

Souvent, on clique pour passer à la start-up suivante alors qu'une nouvel orateur prend la parole sur la start-up en cours: du retard s'accumule sur le temps de parole de la start-up suivante.

- [x] Permettre de passer à la start-up suivante avec les flèches du clavier #20 #21
- [x] Permettre de passer à la start-up précédente avec les flèches du clavier #20 #21
- [ ] Afficher les key bindings
- [ ] Afficher l'écran de la start-up précédente avec le temps qu'il lui restait
- [ ] N'autoriser le retour en arrière que si le temps ne dépasse pas le temps alloué

**Comment by gregoirenovel** [comment]
Il reste trois point à traiter :

> Afficher les key bindings

Ils sont intuitifs et standards (les flêches du clavier), et les afficher compliquerait l'UI et le code pour un gain assez faible. À la limite on peut documenter ça dans le README.

> Afficher l'écran de la start-up précédente avec le temps qu'il lui restait

Prendrait trop de place, pas de rationale clair, et le système actuel semble bien fonctionner.

> N'autoriser le retour en arrière que si le temps ne dépasse pas le temps alloué

Un peu trop ridige, pas de rationale clair ni d'exemple réel constaté
