### ISSUE TITLE
Prévoir un opt-in des produits via une commande Slack

### ISSUE THREAD

**Issue by Morendil** [betagouv/standup#26]
Actuellement, on passe en revue la liste des produits et pour un certain nombre on se retrouve à dire "personne n'est présent pour en parler, RAS".

Afin de garantir l'énergie et la réactivité des personnes qui présentent les avancées ou les difficultés rencontrées sur leur produit, prévoir que la liste des produits passés en revue soit construite dynamiquement le mercredi matin par "opt in", par exemple en tapant sur Slack
`  /jevaispitcher monproduit`

**Comment by gregoirenovel** [comment]
Je ferme car :
- l'irritant n'est visiblement pas assez fort pour que quelqu'un se saissise de ce problème
- je pense que ça ne marchera pas (friction trop forte)
