### ISSUE TITLE
Retirer du standup les Start-up en consolidation qui ne sont plus incubées

### ISSUE THREAD

**Issue by HelaG** [betagouv/standup#34]
Avec le passage en `consolidation` de ce qu'on appelait `sucess` apparaissent maintenant des Start-up d'Etat qui ne sont plus incubées (Retraite, ANAH, API Drones...)

**Comment by gregoirenovel** [comment]
C'est reglé, c'est juste que ça n'a pas été déployé, cf. https://github.com/betagouv/standup/pull/32#issuecomment-400609865.

Ça fait de nombreuses fois que je fais ce que je peux pour ne pas être bloquant sur ce point là, mais personne ne veut visiblement faire l'effort de monter en compétences sur ce sujet là.

Je viens de faire le deploy, le problème n'apparaitra plus au prochain standup.
