### ISSUE TITLE
Forked and in use for the EIG program @ Etalab

### ISSUE THREAD

**Issue by AntoineAugusti** [betagouv/standup#45]
Hello,

Just a quick note to let you know that we've forked this repo and we're going to use it for the Entrepreneur d'Intérêt Général program @ Etalab: https://github.com/entrepreneur-interet-general/standup.

In this commit https://github.com/entrepreneur-interet-general/standup/commit/87224acc15d62f771b9a10eac0dbcdc395ec892b I've used an hardcoded JSON if someone wants to do the same

**Comment by gregoirenovel** [comment]
Thanks @AntoineAugusti! I've updated our README (see b7ce44c) to include a link to your fork and the relevant commit.
