### ISSUE TITLE
Add "pré-incubation" slide

### ISSUE THREAD

**Issue by monbocal** [betagouv/standup#48]
Je suis en train d'essayer d'ajouter une slide "Pré-incubation" avec une description dans la Standup Machine.

Je suis très perdu dans le code et n'arrive pas à trouver où ajouter cette exception, je crois bien que ce n'est pas encore géré.

A mon avis le mieux à faire serait de rajouter une startup card dans "whitelist" avec les informations, qu'en penses-tu @gregoirenovel ?

**Comment by gregoirenovel** [comment]
Il faut :
1. Rajouter la startup au tableau `EXTRA_STARTUPS` dans [`routes/index.js`](https://github.com/betagouv/standup/blob/master/app/routes/index.js)
2. Puis ajouter l'`id` de la startup ajoutée à ce tableau au tableau `WHITELIST` de [`components/standup-desk.js`](https://github.com/betagouv/standup/blob/master/app/components/standup-deck.js)

**Comment by gregoirenovel** [comment]
Done with #49
